<h1><u>Add a meetup</u></h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formRow($form->get('title')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('description')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('start')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('end')) ?>
</div>

<div class="form-group">
    <?= $this->formInput($form->get('submit')) ?>
</div>


<?= $this->form()->closeTag($form); ?>
