<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new</a>

<div class="form-group">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tr>
                <th>Nom/Date</th>
                <th>Action</th>
            </tr>
            <?php foreach ($this->meetups as $meetup): ?>
                <tr>
                    <td>
                        <h2 class=""><strong><?= $meetup->getTitle() ?></strong></h2>
                        <p>Du <span><?= date_format($meetup->getStart(),'d-m-Y') ?></span> au <span><?=  date_format($meetup->getEnd(),'d-m-Y') ?></span></p>
                    </td>
                    <td>
                        <div>
                            <a href="<?= $this->url('meetup/get'); ?><?= $meetup->getId() ?>" class="btn btn-primary">Accéder</a>
                            <a href="<?= $this->url('meetup/edit'); ?><?= $meetup->getId() ?>" class="btn btn-default">Modifier</a>
                            <a href="<?= $this->url('meetup/delete'); ?><?= $meetup->getId() ?>" class="btn btn-danger">Supprimer</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

</div>


