<h1><u>Add a participant</u></h1>

<?php
$form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formRow($form->get('name')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('job')) ?>
</div>

<div class="form-group">
    <?= $this->formInput($form->get('submit')) ?>
</div>


<?= $this->form()->closeTag($form); ?>
