<h1>Participant</h1>

<a href="<?= $this->url('participant/add'); ?>" class="btn btn-primary">Add new</a>

<div class="form-group">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tr>
                <th>Nom</th>
                <th>Job</th>
                <th>Action</th>
            </tr>
            <?php foreach ($this->participants as $participant): ?>
                <tr>
                    <td>
                        <h2 class=""><strong><?= $participant->getName() ?></strong></h2>
                    </td>
                    <td>
                        <p><?= $participant->getJob() ?></p>
                    </td>
                    <td>
                        <div>
                            <a href="<?= $this->url('participant/get'); ?><?= $participant->getId() ?>" class="btn btn-primary">Accéder</a>
                            <a href="<?= $this->url('participant/edit'); ?><?= $participant->getId() ?>" class="btn btn-default">Modifier</a>
                            <a href="<?= $this->url('participant/delete'); ?><?= $participant->getId() ?>" class="btn btn-danger">Supprimer</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            <?php if(sizeof($this->participants) <= 0): ?>
                <td>
                    <p>Aucun participant.</p>
                </td>
                <td></td>
            <?php endif ?>
        </table>
    </div>

</div>


